// @ts-nocheck
"use client"

import React, { useState, useEffect, useMemo, useRef, useCallback } from 'react'
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { cn } from '@/lib/utils'

// --- EXPORT LIBRARIES ---
import ExcelJS from 'exceljs';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { saveAs } from 'file-saver';
import { get, set, isEqual } from 'lodash';

import { CalendarIcon, Download, Save, FileText, Image as ImageIcon, FileSpreadsheet, Edit, Eye, FileUp, History, Trash2, RefreshCw } from 'lucide-react';
import { individualsFormSections, genderOptions } from '../../add/onboarding-older/BasicInformationFormFields'
import { supabase } from '@/lib/supabase'
import { masterFieldsService } from '@/lib/services/masterFields';
import { SearchableSelect } from '@/components/ui/searchable-select';
import toast from 'react-hot-toast'
import {
  generateFullPostalAddress,
  generateFullResidentialAddress,
  shouldFieldTriggerPhysicalAddressUpdate,
  shouldFieldTriggerPostalAddressUpdate
} from '@/utils/addressUtils'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog"


// --- Type Definitions ---
interface Individual {
  id: string;
  full_name?: string;
  [key: string]: any;
}

interface FormField {
  id: number;
  name: string;
  label: string;
  fieldType?: string;
  type?: string;
  placeholder?: string;
  source?: string;
  section?: string;
  disabled?: boolean;
  staticOptions?: string;
  dataPath?: string;
  dataSource?: {
    category: string;
    application?: string;
    subOptionsField?: string;
    masterFieldId?: string;
    dependsOn?: string;
  };
  dependsOn?: string;
  auto?: boolean;
}

interface FieldOptionsResult {
  type: 'standard' | 'dependent';
  allOptions: { label: string; value: string }[];
  manualMapping?: Record<string, { label: string; name?: string; value?: string }[]>;
  parentFieldName?: string;
  parentValueToLabelMap?: Record<string, string>;
}

// --- Helper Functions ---
const hasValue = (value) => {
  if (value === null || value === undefined) return false;
  if (typeof value === 'string' && value.trim() === '') return false;
  if (Array.isArray(value) && value.length === 0) return false;
  if (typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === 0) return false;
  return true;
};

const getAutoGeneratedValue = (fieldName: string, formData: Record<string, any>): string => {
  if (fieldName === 'full_residential_address') return generateFullResidentialAddress(formData);
  if (fieldName === 'full_postal_address') return generateFullPostalAddress(formData);
  return '';
};

const isAutoField = (field: FormField): boolean => {
  if (typeof field.auto === 'boolean') return field.auto;
  return field.name === 'full_residential_address' || field.name === 'full_postal_address';
};

const colIndexToLetter = (colIndex: number): string => {
  let letter = '';
  let n = colIndex;
  while (n > 0) {
    const mod = (n - 1) % 26;
    letter = String.fromCharCode(65 + mod) + letter;
    n = Math.floor((n - 1) / 26);
  }
  return letter;
};

const toSafeRangeName = (str: string): string =>
  String(str)
    .replace(/[^a-zA-Z0-9]/g, '_')
    .replace(/_+/g, '_')
    .substring(0, 150);

const buildExcelSafeSubstitute = (cellRef: string): string => {
  return `SUBSTITUTE(${cellRef}," ","_")`;
};

const normalizeForMatch = (value: any) =>
  String(value ?? '').trim().toLowerCase().replace(/[\s_-]+/g, '');

const mapSelectValueToLabel = async (
  field: FormField | undefined,
  rawValue: any,
  sourceData: Record<string, any>,
  masterFieldsOptions: Record<string, any[]> = {}
) => {
  if (!field || field.type !== 'select' || !hasValue(rawValue)) return rawValue;
  if (!field.dataSource?.masterFieldId) return rawValue;

  const masterField = masterFieldsService.getMasterFieldById(field.dataSource.masterFieldId);
  if (!masterField) return rawValue;

  const raw = String(rawValue).trim();
  const matchOption = (options: any[]) => {
    const matched = (options || []).find((opt: any) => {
      const optionValue = String(opt?.value ?? opt?.name ?? opt?.label ?? '').trim();
      const optionLabel = String(opt?.label ?? opt?.name ?? opt?.value ?? '').trim();
      return (
        normalizeForMatch(optionValue) === normalizeForMatch(raw) ||
        normalizeForMatch(optionLabel) === normalizeForMatch(raw)
      );
    });
    if (!matched) return null;
    return String(matched?.label ?? matched?.name ?? matched?.value ?? raw);
  };

  if (masterField.options?.isDependencyConfig) {
    const manualMapping: Record<string, any[]> = masterField.options?.manualMapping || {};
    const flattenOptions = Object.values(manualMapping).flat();
    return matchOption(flattenOptions) || rawValue;
  }

  try {
    const options = await masterFieldsService.fetchDropdownOptions(masterField);
    return matchOption(options) || rawValue;
  } catch {
    return rawValue;
  }
};

const buildIndividualFullResidentialFormulaFromRefs = (refs: Record<string, string>): string => {
  const piece = (fieldName: string, prefix = '') => {
    const r = refs[fieldName];
    if (!r) return '""';
    if (prefix) return `IF(${r}<>"","${prefix}"&${r}&", ","")`;
    return `IF(${r}<>"",${r}&", ","")`;
  };
  const concat = `CONCATENATE(${[
    piece('apartment_name'),
    piece('apartment_number'),
    piece('road_name'),
    piece('area_name'),
    piece('town'),
    piece('city'),
    piece('county'),
    piece('sub_county'),
    piece('country'),
    piece('plot_number', 'L.R No. '),
  ].join(',')})`;
  return `IF(RIGHT(${concat},2)=", ",LEFT(${concat},LEN(${concat})-2),${concat})`;
};

const buildIndividualFullPostalFormulaFromRefs = (refs: Record<string, string>): string => {
  const postalRef = refs.postal_address;
  const codeRef = refs.postal_code;
  const townRef = refs.postal_town;
  if (!postalRef) return '""';
  const concat = `CONCATENATE("P.O. Box "&${postalRef},", ",${codeRef ? `IF(${codeRef}<>"",${codeRef}&", ","")` : '""'},${townRef ? `IF(${townRef}<>"",${townRef},"")` : '""'})`;
  return `IF(${postalRef}="","",IF(RIGHT(${concat},2)=", ",LEFT(${concat},LEN(${concat})-2),${concat}))`;
};

const applyIndividualAddressFormulas = (
  worksheet: ExcelJS.Worksheet,
  fieldRowMap: Record<string, number>,
  valueColumn = 7
) => {
  const valueRef = (fieldName: string) => {
    const row = fieldRowMap[fieldName];
    return row ? `$${colIndexToLetter(valueColumn)}$${row}` : null;
  };

  const refs = {
    apartment_name: valueRef('apartment_name'),
    apartment_number: valueRef('apartment_number'),
    road_name: valueRef('road_name'),
    area_name: valueRef('area_name'),
    town: valueRef('town'),
    city: valueRef('city'),
    county: valueRef('county'),
    sub_county: valueRef('sub_county'),
    country: valueRef('country'),
    plot_number: valueRef('plot_number'),
    postal_address: valueRef('postal_address'),
    postal_code: valueRef('postal_code'),
    postal_town: valueRef('postal_town'),
  };

  const fullResidentialRow = fieldRowMap.full_residential_address;
  if (fullResidentialRow) {
    worksheet.getCell(fullResidentialRow, valueColumn).value = {
      formula: buildIndividualFullResidentialFormulaFromRefs(refs),
    };
  }

  const fullPostalRow = fieldRowMap.full_postal_address;
  if (fullPostalRow) {
    worksheet.getCell(fullPostalRow, valueColumn).value = {
      formula: buildIndividualFullPostalFormulaFromRefs(refs),
    };
  }
};

const resolveDisplayLabel = (
  rawValue: any,
  optData: FieldOptionsResult | undefined
): string => {
  if (!hasValue(rawValue)) return '';
  if (!optData) return String(rawValue);

  const match = optData.allOptions.find(
    o => String(o.value).toLowerCase() === String(rawValue).toLowerCase()
      || String(o.label).toLowerCase() === String(rawValue).toLowerCase()
  );
  return match ? match.label : String(rawValue);
};

const historyFieldLabelMap = {
  'email.primary': 'Email Address',
  'email.alternative': 'Alternative Email',
  'phone.abroad.primary': 'Primary Mobile (Abroad)',
  'phone.abroad.secondary': 'Secondary Mobile (Abroad)',
  'phone.kenyan.primary': 'Primary Mobile (Kenyan)',
  'phone.kenyan.secondary': 'Secondary Mobile (Kenyan)',
  'phone.whatsapp': 'Broadcast WhatsApp Number',
  'phone.office number': 'Office Phone Number',
  'building.name': 'Apartment Name',
  'building.number': 'Apartment Number',
  'building.estate': 'Estate',
  'location.area': 'Area Name',
  'location.city': 'City',
  'location.road': 'Road Name',
  'location.town': 'Town',
  'location.county': 'County',
  'location.sub_county': 'Sub County',
  'location.plot_number': 'Plot Number',
  'nearest_landmark': 'Nearest Landmark',
  'full_address': 'Full Residential Address',
  'address': 'Postal Address',
  'code': 'Postal Code',
  'town': 'Postal Town',
  'full_postal_address': 'Full Postal Address'
};

const flattenHistoryRecord = (record, basePath = '') => {
  let flattened = {};
  for (const key in record) {
    if (!record.hasOwnProperty(key) || key === 'updated_at') continue;
    const newPath = basePath ? `${basePath}.${key}` : key;
    const value = record[key];
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      Object.assign(flattened, flattenHistoryRecord(value, newPath));
    } else if (hasValue(value)) {
      const label = historyFieldLabelMap[newPath] || newPath.replace(/_/g, ' ');
      flattened[label] = value;
    }
  }
  return flattened;
};

// --- Child Components ---
const HistoryRecordViewer = ({ data }) => {
  const flattenedData = flattenHistoryRecord(data);
  const updatedAt = data.updated_at || data.email?.updated_at || data.phone?.updated_at;

  if (Object.keys(flattenedData).length === 0) {
    return <p className="text-sm text-gray-500">This historical record contains no data.</p>;
  }

  return (
    <div>
      {updatedAt && (
        <p className="text-xs text-gray-500 mb-3">
          Recorded on: {new Date(updatedAt).toLocaleString()}
        </p>
      )}
      <dl>
        {Object.entries(flattenedData).map(([label, value]) => (
          <div key={label} className="grid grid-cols-2 gap-4 py-2 border-b border-gray-100 last:border-b-0">
            <dt className="text-sm font-medium text-gray-600 capitalize">{label}</dt>
            <dd className="text-sm text-gray-800 break-words">{String(value)}</dd>
          </div>
        ))}
      </dl>
    </div>
  );
};


const renderFieldInput = (
  field: FormField,
  value: any,
  formData: Record<string, any>,
  handleChange: (fieldPath: string, value: any) => void,
  isDisabled: boolean,
  masterFieldsOptions: Record<string, any[]>,
  dependentOptions: Record<string, any[]> = {}
) => {
  const fieldPath = field.dataPath || field.name;
  const isAutoGenerated = isAutoField(field);
  const isLocked = isDisabled || isAutoGenerated;
  const lockReason = isAutoGenerated
    ? 'Locked: this field is auto-generated and cannot be edited.'
    : 'Locked: switch to Edit Mode to update this field.';

  let displayValue = value;
  if (isAutoGenerated) {
    displayValue = getAutoGeneratedValue(field.name, formData) || value;
  }

  const hasData = hasValue(displayValue);
  const emptyViewText = isAutoGenerated ? 'Auto-generated (read-only)' : 'missing';

  const commonInputClass = cn(
    "w-full transition-all duration-200 rounded-lg h-10 text-sm",
    hasData ? "bg-blue-50" : "bg-white",
    isLocked
      ? "bg-transparent border-transparent shadow-none cursor-default focus:ring-0 focus-visible:ring-0 focus-visible:ring-offset-0"
      : "border-gray-200 focus:border-blue-400 focus:ring-2 focus:ring-blue-100 shadow-sm",
    isLocked && !hasData && "text-red-500"
  );

  if (isAutoGenerated) {
    return (
      <Input
        type="text"
        value={hasData ? displayValue : (isLocked ? 'Auto-generated when data is available' : '')}
        placeholder={field.placeholder}
        disabled
        readOnly
        className={cn(
          commonInputClass,
          "bg-gradient-to-r from-blue-50 to-indigo-50 border-blue-200 text-blue-700 cursor-not-allowed",
          !hasData && isLocked && "text-blue-500 italic text-sm"
        )}
        title="Locked: this field is auto-generated from other form fields."
      />
    );
  }

  let options: { value: string; label: string }[] = [];
  if (field.name in dependentOptions) {
    options = dependentOptions[field.name] || [];
  } else if (field.dataSource?.category) {
    const categoryData = masterFieldsOptions[field.dataSource.category] || [];
    options = categoryData.map(opt => ({
      value: String(opt.value),
      label: opt.label || opt.value,
    }));
  } else if (field.staticOptions === 'genderOptions') {
    options = genderOptions;
  }

  switch (field.type) {
    case 'select': {
      const selectedOption = options.find((opt) =>
        String(opt.value).toLowerCase() === String(value ?? '').toLowerCase() ||
        String(opt.label).toLowerCase() === String(value ?? '').toLowerCase()
      );
      const selectedValue = selectedOption ? selectedOption.value : '';
      const hasNoOptions = options.length === 0;

      if (isLocked) {
        let selectDisplayValue = emptyViewText;
        if (hasData) {
          selectDisplayValue = selectedOption
            ? (selectedOption.label || selectedOption.value)
            : value || emptyViewText;
        } else if (hasNoOptions) {
          selectDisplayValue = "No options available";
        }
        return (
          <Input
            type="text"
            value={selectDisplayValue}
            readOnly
            title={lockReason}
            className={cn(commonInputClass, hasNoOptions && !hasData && "text-red-500")}
          />
        );
      }

      return (
        <SearchableSelect
          value={selectedValue}
          onValueChange={(newValue) => handleChange(fieldPath, newValue)}
          options={options}
          placeholder={hasNoOptions ? "No options available" : (field.placeholder || `Select ${field.label.toLowerCase()}`)}
          disabled={field.disabled || hasNoOptions}
          emptyMessage={hasNoOptions ? "No options available" : `No ${field.label.toLowerCase()} found.`}
          searchPlaceholder={`Search ${field.label.toLowerCase()}...`}
          buttonClassName={cn(commonInputClass, (!selectedValue || hasNoOptions) && "text-muted-foreground")}
          popoverClassName="w-[var(--radix-popover-trigger-width)]"
        />
      );
    }
    case 'date':
      if (isLocked) {
        return (
          <div className="relative">
            <Input
              type="text"
              value={hasData ? new Date(value).toLocaleDateString() : emptyViewText}
              readOnly
              title={lockReason}
              className={cn(commonInputClass, 'pl-10')}
            />
            <CalendarIcon className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
          </div>
        );
      }
      const dateValue = new Date(value);
      const formattedDate = value && !isNaN(dateValue.getTime()) ? dateValue.toISOString().split('T')[0] : '';
      return (
        <div className="relative">
          <Input type="date" value={formattedDate} onChange={(e) => handleChange(fieldPath, e.target.value)} disabled={field.disabled} className={cn(commonInputClass, 'pl-10')} />
          <CalendarIcon className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
        </div>
      );
    default:
      return (
        <Input
          type={field.type || 'text'}
          value={isLocked && !hasData ? emptyViewText : (value || '')}
          placeholder={isLocked ? '' : (field.placeholder || `Enter ${field.label.toLowerCase()}...`)}
          onChange={(e) => handleChange(fieldPath, e.target.value)}
          readOnly={isLocked}
          disabled={field.disabled || isAutoGenerated}
          title={isLocked ? lockReason : undefined}
          className={commonInputClass}
        />
      );
  }
};

const TableSection = ({
  fields,
  formData,
  handleChange,
  isDisabled,
  isLoading = false,
  masterFieldsOptions,
  dependentOptions,
  individual,
  onHistoryIconClick,
  isExporting = false,
  visibleColumns = { fieldType: true, method: true, source: true }
}: {
  fields: FormField[],
  formData: Record<string, any>,
  handleChange?: (path: string, value: any) => void,
  isDisabled: boolean,
  isLoading?: boolean,
  masterFieldsOptions: Record<string, any[]>,
  dependentOptions?: Record<string, any[]>,
  individual?: Individual,
  onHistoryIconClick?: (title: string, data: any[], section: string) => void,
  isExporting?: boolean,
  visibleColumns?: { fieldType: boolean, method: boolean, source: boolean }
}) => {
  const fieldsBySection = useMemo(() => fields.reduce<Record<string, FormField[]>>((acc, field) => {
    const section = field.section || 'Other';
    acc[section] = acc[section] || [];
    acc[section].push(field);
    return acc;
  }, {}), [fields]);

  const sections = Object.entries(fieldsBySection);
  const sectionDataKeys = { 'Contact Details': 'contact_details', 'Residential Address': 'residential_address_details', 'Postal Address': 'postal_address_details' };
  const dynamicColSpan = 2 + (visibleColumns.fieldType ? 1 : 0) + (visibleColumns.method ? 1 : 0) + (visibleColumns.source ? 1 : 0);

  const tableContainerClass = isExporting
    ? "bg-white"
    : "mb-4 bg-white rounded-sm shadow-sm border border-gray-100 overflow-hidden";

  return (
    <div className={tableContainerClass}>
      <div className={isExporting ? "" : "overflow-y-auto max-h-[800px]"}>
        <Table className="min-w-full divide-y divide-gray-100">
          {!isExporting && (
            <TableHeader className="sticky top-0 bg-blue-500 z-10">
              <TableRow className="hover:bg-transparent">
                <TableHead className="w-[60px] text-white border-r border-gray-100">#</TableHead>
                <TableHead className="text-white border-r border-gray-100">Field</TableHead>
                {visibleColumns.fieldType && <TableHead className="w-[150px] text-white border-r border-gray-100">Field Type</TableHead>}
                {visibleColumns.method && <TableHead className="w-[150px] text-white border-r border-gray-100">Method</TableHead>}
                {visibleColumns.source && <TableHead className="w-[150px] text-white border-r border-gray-100">Source</TableHead>}
                <TableHead className="text-white">Value</TableHead>
              </TableRow>
            </TableHeader>
          )}
          <TableBody>
            {isLoading ? (
              <TableRow>
                <TableCell colSpan={dynamicColSpan} className="py-10 text-center text-slate-600">
                  <div className="inline-flex items-center gap-2">
                    <RefreshCw className="h-4 w-4 animate-spin" />
                    <span>Loading individual data...</span>
                  </div>
                </TableCell>
              </TableRow>
            ) : sections.map(([section, sectionFields]) => {
              const dataKey = sectionDataKeys[section];
              const historyData = dataKey ? get(individual, `${dataKey}.history`, []) : [];
              const hasHistory = Array.isArray(historyData) && historyData.length > 0;

              return (
                <React.Fragment key={section}>
                  <TableRow className="bg-gradient-to-r from-blue-50 to-blue-100">
                    <TableCell colSpan={dynamicColSpan} className="py-3 px-6 font-semibold text-blue-800 border-b border-blue-200 text-sm">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center">
                          <span className="inline-block w-1.5 h-4 bg-blue-500 rounded-full mr-2"></span>
                          {section}
                          {section === 'Residential Address' && <span className="ml-2 text-xs text-blue-600">(Full address auto-generated)</span>}
                          {section === 'Postal Address' && <span className="ml-2 text-xs text-blue-600">(Full postal address auto-generated)</span>}
                        </div>
                        {hasHistory && !isExporting && (
                          <Button variant="ghost" size="sm" className="h-auto px-2 py-1 text-blue-600 hover:bg-blue-200" onClick={() => onHistoryIconClick(section, historyData, section)}>
                            <History className="h-4 w-4 mr-1" /> History
                          </Button>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                  {isExporting && (
                    <TableRow className="bg-blue-500">
                      <TableCell className="w-[60px] text-white border-r border-gray-100 font-bold">#</TableCell>
                      <TableCell className="text-white border-r border-gray-100 font-bold">Field</TableCell>
                      {visibleColumns.fieldType && <TableCell className="w-[150px] text-white border-r border-gray-100 font-bold">Field Type</TableCell>}
                      {visibleColumns.method && <TableCell className="w-[150px] text-white border-r border-gray-100 font-bold">Method</TableCell>}
                      {visibleColumns.source && <TableCell className="w-[150px] text-white border-r border-gray-100 font-bold">Source</TableCell>}
                      <TableCell className="text-white font-bold">Value</TableCell>
                    </TableRow>
                  )}
                  {sectionFields.map((field) => {
                    const fieldValue = get(formData, field.dataPath || field.name);
                    const isAuto = isAutoField(field);
                    return (
                      <TableRow key={field.name} className={cn("border-b border-gray-100", isAuto && "bg-gray-25")}>
                        <TableCell className="py-2 px-4 text-sm text-gray-500 border-r border-gray-100 text-center">{field.id}</TableCell>
                        <TableCell className="py-3 px-4 border-r border-gray-100">
                          <div className="font-medium text-gray-800">
                            {field.label}
                            {isAuto && <span className="ml-1 text-xs text-gray-500">(auto)</span>}
                          </div>
                        </TableCell>
                        {visibleColumns.fieldType && (
                          <TableCell className="py-2 px-3 text-[11px] text-gray-500 border-r border-gray-50 italic capitalize">
                            {field.fieldType || field.type || 'text'}
                          </TableCell>
                        )}
                        {visibleColumns.method && (
                          <TableCell className="py-2 px-3 border-r border-gray-50">
                            <span className={cn(
                              "px-2 py-0.5 rounded text-[9px] font-bold uppercase",
                              isAuto ? "bg-indigo-100 text-indigo-700" : "bg-amber-100 text-amber-700"
                            )}>
                              {isAuto ? 'Auto' : 'Manual'}
                            </span>
                          </TableCell>
                        )}
                        {visibleColumns.source && (
                          <TableCell className="py-2 px-4 text-sm text-gray-500 border-r border-gray-100">
                            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                              {field.source || 'N/A'}
                            </span>
                          </TableCell>
                        )}
                        <TableCell className="py-2 px-4">
                          {renderFieldInput(
                            field,
                            fieldValue,
                            formData,
                            handleChange || (() => { }),
                            isDisabled,
                            masterFieldsOptions,
                            dependentOptions
                          )}
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </React.Fragment>
              );
            })}
          </TableBody>
        </Table>
      </div>
    </div>
  );
};

// --- Main Component ---
export default function BasicInfo({ individual }: { individual: Individual }) {
  const [localIndividual, setLocalIndividual] = useState(individual);
  const [formData, setFormData] = useState<Record<string, any>>({});
  const [initialData, setInitialData] = useState<Record<string, any>>({});
  const [isEditMode, setIsEditMode] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isDataLoading, setIsDataLoading] = useState(true);
  const [isExporting, setIsExporting] = useState(false);
  const [confirmation, setConfirmation] = useState<{ isOpen: boolean; title: string; description: string; onConfirm: (updateType: 'overwrite' | 'history') => void } | null>(null);
  const [historyModal, setHistoryModal] = useState({ isOpen: false, title: '', data: [], section: '' });
  const [clearHistoryConfirmation, setClearHistoryConfirmation] = useState<{ isOpen: boolean; onConfirm: () => void; title: string; description: string } | null>(null);

  const componentRef = useRef<HTMLDivElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [masterFieldsOptions, setMasterFieldsOptions] = useState<Record<string, any[]>>({});
  const [dependentOptions, setDependentOptions] = useState<Record<string, any[]>>({});
  const [masterFieldsReady, setMasterFieldsReady] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const allFields = useMemo(() => Object.values(individualsFormSections).flatMap(s => s.fields.map(f => ({ ...f, section: s.title }))), []);
  const fieldByName = useMemo(() => Object.fromEntries(allFields.map((field) => [field.name, field])), [allFields]);
  const fieldByPath = useMemo(() => Object.fromEntries(allFields.map((field) => [field.dataPath || field.name, field])), [allFields]);
  const sectionFieldNames = useMemo(() => ({
    'Contact Details': ['email_address', 'alternative_email', 'personal_mobile_num_abroad_1', 'personal_mobile_num_abroad_2', 'personal_mobile_num_kenyan_1', 'personal_mobile_num_kenyan_2', 'broadcast_whatsapp_number', 'office_phone_number', 'website'],
    'Residential Address': ['country', 'apartment_name', 'apartment_number', 'area_name', 'city', 'road_name', 'town', 'county', 'sub_county', 'plot_number', 'estate', 'nearest_landmark'],
    'Postal Address': ['postal_address', 'postal_code', 'postal_town'],
  }), []);
  const syncFieldValue = useCallback((target: Record<string, any>, field: FormField | undefined, value: any) => {
    if (!field) return;
    const fieldPath = field.dataPath || field.name;
    set(target, fieldPath, value);
    if (fieldPath !== field.name) {
      target[field.name] = value;
    }
  }, []);
  const buildMergedFormData = useCallback((source: Individual) => {
    const mergedData: Record<string, any> = JSON.parse(JSON.stringify(source || {}));
    const contact = get(source, 'contact_details.current', {});
    const residential = get(source, 'residential_address_details.current', {});
    const postal = get(source, 'postal_address_details.current', {});

    mergedData.email_address = get(contact, 'email.primary', '');
    mergedData.alternative_email = get(contact, 'email.alternative', '');
    mergedData.personal_mobile_num_abroad_1 = get(contact, 'phone.abroad.primary', '');
    mergedData.personal_mobile_num_abroad_2 = get(contact, 'phone.abroad.secondary', '');
    mergedData.personal_mobile_num_kenyan_1 = get(contact, 'phone.kenyan.primary', '');
    mergedData.personal_mobile_num_kenyan_2 = get(contact, 'phone.kenyan.secondary', '');
    mergedData.broadcast_whatsapp_number = get(contact, 'phone.whatsapp', '');
    mergedData.office_phone_number = get(contact, 'phone.office number', '');
    mergedData.website = get(contact, 'website', '');

    mergedData.country = get(residential, 'location.country', '');
    mergedData.apartment_name = get(residential, 'building.name', '');
    mergedData.apartment_number = get(residential, 'building.number', '');
    mergedData.estate = get(residential, 'building.estate', '');
    mergedData.area_name = get(residential, 'location.area', '');
    mergedData.city = get(residential, 'location.city', '');
    mergedData.road_name = get(residential, 'location.road', '');
    mergedData.town = get(residential, 'location.town', '');
    mergedData.county = get(residential, 'location.county', '');
    mergedData.sub_county = get(residential, 'location.sub_county', '');
    mergedData.plot_number = get(residential, 'location.plot_number', '');
    mergedData.nearest_landmark = get(residential, 'nearest_landmark', '');
    mergedData.full_residential_address = get(residential, 'full_address', get(residential, 'full_residential_address', ''));

    mergedData.postal_address = get(postal, 'address', '');
    mergedData.postal_code = get(postal, 'code', '');
    mergedData.postal_town = get(postal, 'town', '');
    mergedData.full_postal_address = get(postal, 'full_postal_address', '');

    allFields.forEach((field) => {
      if (Object.prototype.hasOwnProperty.call(mergedData, field.name)) {
        syncFieldValue(mergedData, field, mergedData[field.name]);
        return;
      }

      const fieldPath = field.dataPath || field.name;
      const value = get(mergedData, fieldPath);
      if (fieldPath !== field.name && value !== undefined) {
        mergedData[field.name] = value;
      }
    });

    if (hasValue(mergedData.full_residential_address)) {
      set(mergedData, 'residential_address_details.full_residential_address', mergedData.full_residential_address);
      set(mergedData, 'residential_address_details.current.full_residential_address', mergedData.full_residential_address);
      set(mergedData, 'residential_address_details.current.full_address', mergedData.full_residential_address);
    }
    if (hasValue(mergedData.full_postal_address)) {
      set(mergedData, 'postal_address_details.current.full_postal_address', mergedData.full_postal_address);
    }

    return mergedData;
  }, [allFields, syncFieldValue]);

  // Initialize master fields
  useEffect(() => {
    const initializeMasterFields = async () => {
      try {
        await masterFieldsService.fetchMasterFields();
        const optionsMap: Record<string, any[]> = {};
        const uniqueIds = [...new Set(
          allFields
            .filter(f => f.dataSource?.masterFieldId)
            .map(f => f.dataSource!.masterFieldId!)
        )];

        for (const masterFieldId of uniqueIds) {
          try {
            const masterField = masterFieldsService.getMasterFieldById(masterFieldId);
            if (!masterField) continue;

            // Skip dependent fields here — they need a parent value,
            // so we handle them in updateDependentOptions instead.
            if (masterField.options?.isDependencyConfig) continue;

            const options = await masterFieldsService.fetchDropdownOptions(masterField);
            const fieldWithId = allFields.find(f => f.dataSource?.masterFieldId === masterFieldId);
            const category = fieldWithId?.dataSource?.category;
            if (category) optionsMap[category] = options;
          } catch (e) {
            console.error(`Error fetching options for master field ${masterFieldId}:`, e);
          }
        }

        setMasterFieldsOptions(optionsMap);
      } catch (error) {
        console.error('Error initializing master fields:', error);
        setError('Failed to load form options');
      } finally {
        setMasterFieldsReady(true);
        setLoading(false);
      }
    };

    initializeMasterFields();
  }, [allFields]);

  // Update dependent options when form data changes
  useEffect(() => {
    if (!masterFieldsReady) return;

    const updateDependentOptions = async () => {
      const newDependentOptions: Record<string, any[]> = {};

      // Collect all fields that are dependent (isDependencyConfig)
      const dependentFields = allFields.filter(field => {
        if (!field.dataSource?.masterFieldId) return false;
        const masterField = masterFieldsService.getMasterFieldById(field.dataSource.masterFieldId);
        return masterField?.options?.isDependencyConfig === true;
      });

      for (const field of dependentFields) {
        const masterField = masterFieldsService.getMasterFieldById(field.dataSource!.masterFieldId!);
        if (!masterField) continue;

        const manualMapping: Record<string, any[]> = masterField.options?.manualMapping || {};

        // Resolve which field is the parent
        const parentFieldName: string =
          masterField.options?.parentField
          || masterField.options?.dependencyConfig?.parentField
          || field.dataSource?.dependsOn
          || field.dependsOn
          || (field.name === 'sub_county' ? 'county' : '')
          || '';

        if (!parentFieldName) {
          console.warn(`[dependentOptions] No parentFieldName found for field "${field.name}". Skipping.`);
          continue;
        }

        // Resolve the raw stored parent value
        const rawParentValue = formData[parentFieldName] || null;

        if (!rawParentValue) {
          newDependentOptions[field.name] = [];
          continue;
        }

        const parentValue = String(rawParentValue).trim();
        const normalize = (s: any) => String(s ?? '').toLowerCase().replace(/[\s_-]+/g, '');
        const manualMappingKeys = Object.keys(manualMapping);
        const parentCandidates = new Set<string>([parentValue]);

        const directManualKey = manualMappingKeys.find(
          key => normalize(key) === normalize(parentValue)
        );
        if (directManualKey) parentCandidates.add(directManualKey);

        const parentFieldObj = allFields.find(f => f.name === parentFieldName);
        if (parentFieldObj?.dataSource?.masterFieldId) {
          const parentMasterField = masterFieldsService.getMasterFieldById(parentFieldObj.dataSource.masterFieldId);
          if (parentMasterField) {
            try {
              const parentOptions = await masterFieldsService.fetchDropdownOptions(parentMasterField);
              const matchedParent = (parentOptions || []).find((opt: any) => {
                const optValue = String(opt?.value ?? '').trim();
                const optLabel = String(opt?.label ?? opt?.name ?? opt?.value ?? '').trim();
                return normalize(optValue) === normalize(parentValue) || normalize(optLabel) === normalize(parentValue);
              });
              if (matchedParent) {
                const parentId = String(matchedParent?.value ?? '').trim();
                const parentLabel = String(matchedParent?.label ?? matchedParent?.name ?? matchedParent?.value ?? '').trim();
                if (parentId) parentCandidates.add(parentId);
                if (parentLabel) parentCandidates.add(parentLabel);

                const idMappedKey = manualMappingKeys.find(k => normalize(k) === normalize(parentId));
                const labelMappedKey = manualMappingKeys.find(k => normalize(k) === normalize(parentLabel));
                if (idMappedKey) parentCandidates.add(idMappedKey);
                if (labelMappedKey) parentCandidates.add(labelMappedKey);
              }
            } catch (parentOptionsErr) {
              console.warn(`[dependentOptions] Failed to resolve parent option mapping for "${field.name}":`, parentOptionsErr);
            }
          }
        }

        try {
          let options: any[] = [];
          for (const candidate of Array.from(parentCandidates)) {
            if (!candidate) continue;
            options = await masterFieldsService.fetchDropdownOptions(masterField, candidate);
            if (options && options.length > 0) break;
          }

          // Key mismatch fallback
          if (!options || options.length === 0) {
            const matchedKey = manualMappingKeys.find(
              key => Array.from(parentCandidates).some(candidate => normalize(key) === normalize(candidate))
            );

            if (matchedKey) {
              options = await masterFieldsService.fetchDropdownOptions(masterField, matchedKey);

              if (!options || options.length === 0) {
                options = (manualMapping[matchedKey] as any[]).map(opt => ({
                  label: String(opt.label || opt.name || opt.value || ''),
                  value: String(opt.value || opt.name || opt.label || ''),
                })).filter(o => o.label);
              }
            } else {
              options = Object.values(manualMapping)
                .flat()
                .map((opt: any) => ({
                  label: String(opt.label || opt.name || ''),
                  value: String(opt.value || opt.name || ''),
                }))
                .filter(o => o.label);
            }
          }

          newDependentOptions[field.name] = options;

        } catch (error) {
          console.error(`[dependentOptions] Error fetching options for "${field.name}" with parent "${parentValue}":`, error);
          newDependentOptions[field.name] = [];
        }
      }

      setDependentOptions(newDependentOptions);
    };

    updateDependentOptions();
  }, [formData, allFields, masterFieldsReady]);

  useEffect(() => {
    setLocalIndividual(individual);
  }, [individual]);

  const fetchAndSetData = useCallback(async (individualSource?: Individual) => {
    const source = individualSource || localIndividual;
    if (!source?.id) {
      setIsDataLoading(false);
      return;
    }

    setIsDataLoading(true);
    try {
      const mergedData = buildMergedFormData(source);
      setFormData(mergedData);
      setInitialData(JSON.parse(JSON.stringify(mergedData)));
    } catch (fetchError) {
      console.error("Error processing individual information:", fetchError);
      toast.error("Failed to process individual information.");
    } finally {
      setIsDataLoading(false);
    }
  }, [buildMergedFormData, localIndividual]);

  useEffect(() => {
    fetchAndSetData();
  }, [fetchAndSetData]);

  useEffect(() => {
    if (Object.keys(formData).length === 0 || isDataLoading) return;

    const residentialAddress = generateFullResidentialAddress(formData);
    const postalAddress = generateFullPostalAddress(formData);
    const updates: Record<string, any> = {};

    if (residentialAddress && formData.full_residential_address !== residentialAddress) {
      updates.full_residential_address = residentialAddress;
      set(updates, 'residential_address_details.full_residential_address', residentialAddress);
      set(updates, 'residential_address_details.current.full_residential_address', residentialAddress);
      set(updates, 'residential_address_details.current.full_address', residentialAddress);
    }

    if (postalAddress && formData.full_postal_address !== postalAddress) {
      updates.full_postal_address = postalAddress;
      set(updates, 'postal_address_details.current.full_postal_address', postalAddress);
    }

    if (Object.keys(updates).length > 0) {
      setFormData(prev => ({ ...prev, ...updates }));
    }
  }, [
    formData.apartment_name, formData.apartment_number, formData.road_name, formData.area_name,
    formData.town, formData.city, formData.county, formData.sub_county, formData.country,
    formData.plot_number, formData.postal_address, formData.postal_code, formData.postal_town, isDataLoading
  ]);

  const handleInputChange = (fieldPath: string, value: any) => {
    setFormData(prev => {
      const newData = { ...prev };
      const field = fieldByPath[fieldPath];

      set(newData, fieldPath, value);
      if (field && fieldPath !== field.name) {
        newData[field.name] = value;
      }

      if (shouldFieldTriggerPhysicalAddressUpdate(fieldPath) || (field && shouldFieldTriggerPhysicalAddressUpdate(field.name))) {
        const residentialAddress = generateFullResidentialAddress(newData);
        newData.full_residential_address = residentialAddress;
        set(newData, 'residential_address_details.full_residential_address', residentialAddress);
        set(newData, 'residential_address_details.current.full_residential_address', residentialAddress);
        set(newData, 'residential_address_details.current.full_address', residentialAddress);
      }

      if (shouldFieldTriggerPostalAddressUpdate(fieldPath) || (field && shouldFieldTriggerPostalAddressUpdate(field.name))) {
        const postalAddress = generateFullPostalAddress(newData);
        newData.full_postal_address = postalAddress;
        set(newData, 'postal_address_details.current.full_postal_address', postalAddress);
      }

      return newData;
    });
  };

  const hasChanged = (fieldName) => !isEqual(get(formData, fieldName), get(initialData, fieldName));

  const performSave = async (updateType, changedSections) => {
    setIsSaving(true);
    const normalizedFormData = JSON.parse(JSON.stringify(formData));
    await Promise.all(allFields.map(async (field) => {
      const fieldPath = field.dataPath || field.name;
      const rawValue = get(formData, fieldPath);
      const mapped = await mapSelectValueToLabel(field, rawValue, formData, masterFieldsOptions);
      syncFieldValue(normalizedFormData, field, mapped);
    }));

    const individualPayload = {};
    const now = new Date().toISOString();
    const directIndividualFields = ['first_name', 'middle_name', 'last_name', 'full_name', 'gender', 'date_of_birth', 'nationality', 'country_of_birth', 'id_number', 'passport_number', 'alien_number', 'kra_pin', 'nhif_number', 'nssf_number', 'age', 'r_number', 'marital_status'];

    allFields.forEach(field => {
      const fieldPath = field.dataPath || field.name;
      const comparisonKey = fieldPath === field.name ? field.name : field.name;
      if (hasChanged(comparisonKey) && directIndividualFields.includes(field.name)) {
        set(individualPayload, field.name, get(normalizedFormData, field.name));
      }
    });

    if (changedSections.includes('Contact Details') || hasChanged('website')) {
      let history = get(localIndividual, 'contact_details.history', []) || [];
      if (changedSections.includes('Contact Details') && updateType === 'history' && hasValue(get(localIndividual, 'contact_details.current'))) {
        const oldCurrent = get(localIndividual, 'contact_details.current', {});
        const recordToArchive = { ...oldCurrent, updated_at: new Date().toISOString() };
        history.push(recordToArchive);
      }
      individualPayload.contact_details = {
        current: {
          email: {
            primary: normalizedFormData.email_address,
            alternative: normalizedFormData.alternative_email
          },
          phone: {
            abroad: {
              primary: normalizedFormData.personal_mobile_num_abroad_1,
              secondary: normalizedFormData.personal_mobile_num_abroad_2
            },
            kenyan: {
              primary: normalizedFormData.personal_mobile_num_kenyan_1,
              secondary: normalizedFormData.personal_mobile_num_kenyan_2
            },
            whatsapp: normalizedFormData.broadcast_whatsapp_number,
            'office number': normalizedFormData.office_phone_number
          },
          website: normalizedFormData.website,
          updated_at: now
        },
        history, updated_at: now
      };
    }

    if (changedSections.includes('Residential Address')) {
      let history = get(localIndividual, 'residential_address_details.history', []) || [];
      if (updateType === 'history' && hasValue(get(localIndividual, 'residential_address_details.current'))) {
        const oldCurrent = get(localIndividual, 'residential_address_details.current', {});
        history.push({ ...oldCurrent, updated_at: new Date().toISOString() });
      }
      individualPayload.residential_address_details = {
        current: {
          building: {
            name: normalizedFormData.apartment_name,
            estate: normalizedFormData.estate,
            number: normalizedFormData.apartment_number
          },
          location: {
            country: normalizedFormData.country,
            area: normalizedFormData.area_name,
            city: normalizedFormData.city,
            road: normalizedFormData.road_name,
            town: normalizedFormData.town,
            county: normalizedFormData.county,
            sub_county: normalizedFormData.sub_county,
            plot_number: normalizedFormData.plot_number
          },
          full_address: normalizedFormData.full_residential_address,
          full_residential_address: normalizedFormData.full_residential_address,
          nearest_landmark: normalizedFormData.nearest_landmark,
          updated_at: now
        },
        history, updated_at: now
      };
    }

    if (changedSections.includes('Postal Address')) {
      let history = get(localIndividual, 'postal_address_details.history', []) || [];
      if (updateType === 'history' && hasValue(get(localIndividual, 'postal_address_details.current'))) {
        const oldCurrent = get(localIndividual, 'postal_address_details.current', {});
        history.push({ ...oldCurrent, updated_at: new Date().toISOString() });
      }
      individualPayload.postal_address_details = {
        current: { address: normalizedFormData.postal_address, code: normalizedFormData.postal_code, town: normalizedFormData.postal_town, full_postal_address: normalizedFormData.full_postal_address, updated_at: now },
        history, updated_at: now
      };
    }

    try {
      if (Object.keys(individualPayload).length > 0) {
        const { error } = await supabase.from('registry_individuals').update(individualPayload).eq('id', localIndividual.id);
        if (error) throw error;
      }
      toast.success("Changes saved successfully!");
      setIsEditMode(false);

      const { data: updatedIndividual, error: fetchError } = await supabase
        .from('registry_individuals')
        .select('*')
        .eq('id', localIndividual.id)
        .single();

      if (fetchError) {
        toast.error("Saved, but failed to refresh data. Please refresh the page.");
      } else if (updatedIndividual) {
        setLocalIndividual(prevIndividual => ({
          ...prevIndividual,
          ...updatedIndividual,
        }));
        await fetchAndSetData({
          ...localIndividual,
          ...updatedIndividual,
        });
      }

    } catch (error) {
      console.error("Error saving changes:", error);
      toast.error(`Failed to save changes: ${error.message}`);
    } finally {
      setIsSaving(false);
      setConfirmation(null);
    }
  };

  const handleSaveChanges = async () => {
    const changedSections = [];
    Object.entries(sectionFieldNames).forEach(([section, fieldNames]) => {
      if (fieldNames.some(hasChanged)) {
        changedSections.push(section);
      }
    });

    const otherFieldsChanged = allFields
      .filter(f => !Object.keys(sectionFieldNames).includes(f.section || ''))
      .some(field => hasChanged(field.name));

    if (changedSections.length > 0) {
      setConfirmation({
        isOpen: true,
        title: "Confirm Data Update",
        description: `You have modified: ${changedSections.join(', ')}. How would you like to save these changes?`,
        onConfirm: (updateType) => performSave(updateType, changedSections)
      });
    } else if (otherFieldsChanged) {
      performSave('overwrite', []);
    } else {
      toast.info("No changes to save.");
      setIsEditMode(false);
    }
  };

  const handleClearHistory = async (section: string) => {
    const sectionDataKeys = {
      'Contact Details': 'contact_details',
      'Residential Address': 'residential_address_details',
      'Postal Address': 'postal_address_details',
    };
    const dataKey = sectionDataKeys[section];
    if (!dataKey) {
      toast.error("Invalid section to clear history from.");
      return;
    }

    const payload = {
      [dataKey]: {
        ...get(localIndividual, dataKey, {}),
        history: [],
      }
    };

    try {
      const { error } = await supabase.from('registry_individuals').update(payload).eq('id', localIndividual.id);
      if (error) throw error;

      toast.success(`${section} history cleared successfully!`);
      setHistoryModal({ isOpen: false, title: '', data: [], section: '' });

      const { data: updatedIndividual, error: fetchError } = await supabase
        .from('registry_individuals')
        .select('*')
        .eq('id', localIndividual.id)
        .single();

      if (fetchError) {
        toast.error("History cleared, but failed to refresh data. Please refresh the page.");
      } else {
        setLocalIndividual(updatedIndividual);
        await fetchAndSetData(updatedIndividual);
      }

    } catch (error) {
      console.error("Error clearing history:", error);
      toast.error(`Failed to clear history: ${error.message}`);
    } finally {
      setClearHistoryConfirmation(null);
    }
  };

  const fetchAllDropdownOptions = async (fields: FormField[]) => {
    await masterFieldsService.fetchMasterFields();
    const optionsMap: Record<string, FieldOptionsResult> = {};

    for (const field of fields) {
      if (field.staticOptions === 'genderOptions') {
        optionsMap[field.name] = {
          type: 'standard',
          allOptions: genderOptions.map((option) => ({
            label: String(option.label),
            value: String(option.value),
          }))
        };
        continue;
      }

      if (!field.dataSource?.masterFieldId) continue;
      try {
        const masterField = masterFieldsService.getMasterFieldById(field.dataSource.masterFieldId);
        if (!masterField) continue;

        if (masterField.options?.isDependencyConfig) {
          const manualMapping = masterField.options.manualMapping || {};
          const parentFieldName = masterField.options?.parentField
            || field.dataSource?.dependsOn
            || field.dependsOn
            || (field.name === 'sub_county' ? 'county' : '');

          const parentValueToLabelMap: Record<string, string> = {};
          const parentFieldObj = fields.find(f => f.name === parentFieldName);

          if (parentFieldObj?.dataSource?.masterFieldId) {
            const parentMasterField = masterFieldsService.getMasterFieldById(parentFieldObj.dataSource.masterFieldId);
            if (parentMasterField) {
              const parentOptions = await masterFieldsService.fetchDropdownOptions(parentMasterField);
              parentOptions.forEach((option: any) => {
                parentValueToLabelMap[String(option.value)] = String(option.label);
              });
            }
          }

          optionsMap[field.name] = {
            type: 'dependent',
            manualMapping,
            parentFieldName,
            parentValueToLabelMap,
            allOptions: Object.values(manualMapping).flat().map((option: any) => ({
              label: String(option.label || option.name || option.value || ''),
              value: String(option.value || option.name || option.label || ''),
            })).filter(option => option.label)
          };
        } else {
          const raw = await masterFieldsService.fetchDropdownOptions(masterField);
          optionsMap[field.name] = {
            type: 'standard',
            allOptions: raw.map((option: any) => ({
              label: String(option.label),
              value: String(option.value),
            }))
          };
        }
      } catch (fetchError) {
        console.error(fetchError);
      }
    }

    return { optionsMap };
  };

  const EXCEL_COLORS = {
    headerBg: 'FF002060',
    headerFont: 'FFFFFFFF',
    valueBg: 'FFF0F8FF',
    border: 'FFD4D4D4',
    autoBg: 'FFF5F3FF',
  };

  const styleCell = (cell: ExcelJS.Cell, customStyle: any = {}) => {
    cell.font = { name: 'Calibri', size: 10, ...customStyle.font };
    cell.alignment = { vertical: 'middle', horizontal: 'left', wrapText: true, ...customStyle.alignment };
    cell.border = {
      top: { style: 'thin', color: { argb: EXCEL_COLORS.border }, ...customStyle.border?.top },
      left: { style: 'thin', color: { argb: EXCEL_COLORS.border } },
      right: { style: 'thin', color: { argb: EXCEL_COLORS.border } },
      bottom: { style: 'thin', color: { argb: EXCEL_COLORS.border } },
    };
    if (customStyle.fill) cell.fill = customStyle.fill;
  };

  const prepareSheetBase = (worksheet: ExcelJS.Worksheet, reportTitle: string, individualName: string) => {
    worksheet.mergeCells('A1:G1');
    const titleCell = worksheet.getCell('A1');
    titleCell.value = reportTitle;
    titleCell.font = { size: 16, bold: true, color: { argb: EXCEL_COLORS.headerBg } };
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' };

    worksheet.mergeCells('A2:G2');
    worksheet.getCell('A2').value = `Entity: ${individualName} | Export Date: ${new Date().toLocaleString()}`;
    worksheet.getCell('A2').font = { italic: true, color: { argb: 'FF555555' } };

    const headerRow = worksheet.getRow(4);
    headerRow.values = ['#', 'Section', 'Field', 'Field Type', 'Method', 'Source', 'Value'];
    headerRow.height = 25;
    headerRow.eachCell((cell) => {
      styleCell(cell, {
        font: { bold: true, color: { argb: EXCEL_COLORS.headerFont } },
        fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: EXCEL_COLORS.headerBg } },
        alignment: { horizontal: 'center' }
      });
    });

    worksheet.views = [{ state: 'frozen', xSplit: 0, ySplit: 4 }];
    worksheet.columns = [
      { width: 6 },
      { width: 22 },
      { width: 32 },
      { width: 12 },
      { width: 12 },
      { width: 15 },
      { width: 50 },
    ];
  };

  const applyAutoFieldProtection = async (
    worksheet: ExcelJS.Worksheet,
    fields: FormField[],
    fieldRowMap: Record<string, number>
  ) => {
    const lockNote = 'Locked: this field is auto-generated and cannot be edited.';

    fields.forEach((field) => {
      const rowNum = fieldRowMap[field.name];
      if (!rowNum) return;

      const valueCell = worksheet.getCell(rowNum, 7);
      const autoLocked = isAutoField(field);

      valueCell.protection = { locked: autoLocked };
      if (autoLocked) {
        valueCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: EXCEL_COLORS.autoBg } };
        valueCell.note = lockNote;
      }
    });

    await worksheet.protect('auto-generated-lock', {
      selectLockedCells: true,
      selectUnlockedCells: true,
      formatCells: false,
      formatColumns: false,
      formatRows: false,
      insertColumns: false,
      insertRows: false,
      insertHyperlinks: false,
      deleteColumns: false,
      deleteRows: false,
      sort: false,
      autoFilter: false,
      pivotTables: false,
    });
  };

  const handleDownloadTemplate = async () => {
    try {
      const workbook = new ExcelJS.Workbook();
      const worksheet = workbook.addWorksheet('Import Template');
      const dataSheet = workbook.addWorksheet('DropdownLists');
      dataSheet.state = 'hidden';

      const { optionsMap } = await fetchAllDropdownOptions(allFields);
      prepareSheetBase(worksheet, 'INDIVIDUAL DATA IMPORT TEMPLATE', 'NEW INDIVIDUAL');

      const fieldsBySection = allFields.reduce((acc, field) => {
        (acc[field.section] = acc[field.section] || []).push(field);
        return acc;
      }, {});

      let currentRow = 5;
      const fieldRowMap: Record<string, number> = {};

      Object.entries(fieldsBySection).forEach(([sectionName, fields]: [string, any]) => {
        fields.forEach((field, index) => {
          fieldRowMap[field.name] = currentRow;
          const row = worksheet.getRow(currentRow);
          row.values = [field.id, sectionName, field.label, field.fieldType || field.type || 'text', isAutoField(field) ? 'Auto' : 'Manual', field.source || 'Client', ''];

          row.eachCell({ includeEmpty: true }, (cell, colNum) => {
            const customStyle: any = {};
            if (index === 0) customStyle.border = { top: { style: 'medium', color: { argb: EXCEL_COLORS.headerBg } } };
            if (colNum === 7) customStyle.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: EXCEL_COLORS.valueBg } };
            styleCell(cell, customStyle);
          });

          currentRow++;
        });
      });

      applyIndividualAddressFormulas(worksheet, fieldRowMap);

      let listCol = 1;
      allFields.forEach((field) => {
        const rowNum = fieldRowMap[field.name];
        if (!rowNum || field.type !== 'select' || isAutoField(field)) return;

        const optData = optionsMap[field.name];
        const colLetter = dataSheet.getColumn(listCol).letter;

        if (!optData || optData.allOptions.length === 0) {
          dataSheet.getCell(1, listCol).value = "No options found";
          worksheet.getCell(rowNum, 7).dataValidation = { type: 'list', formulae: [`DropdownLists!$${colLetter}$1:$${colLetter}$1`] };
        } else if (optData.type === 'standard') {
          optData.allOptions.forEach((option, index) => {
            dataSheet.getCell(index + 1, listCol).value = option.label;
          });
          worksheet.getCell(rowNum, 7).dataValidation = { type: 'list', formulae: [`DropdownLists!$${colLetter}$1:$${colLetter}$${optData.allOptions.length}`] };
        } else if (optData.type === 'dependent') {
          const parentRow = fieldRowMap[optData.parentFieldName || ''];
          if (parentRow) {
            Object.entries(optData.manualMapping || {}).forEach(([parentId, children]: [string, any], mappingIndex) => {
              const start = (mappingIndex * 500) + 1;
              const parentLabel = optData.parentValueToLabelMap?.[parentId] || parentId;
              const rangeName = `TMPVAL_${toSafeRangeName(field.name)}_${toSafeRangeName(parentLabel)}`;
              children.forEach((child, childIndex) => {
                dataSheet.getCell(start + childIndex, listCol).value = child.label || child.name || child.value;
              });
              workbook.definedNames.add(`DropdownLists!$${colLetter}$${start}:$${colLetter}$${start + children.length - 1}`, rangeName);
            });
            worksheet.getCell(rowNum, 7).dataValidation = {
              type: 'list',
              allowBlank: true,
              formulae: [`=INDIRECT("TMPVAL_${toSafeRangeName(field.name)}_"&${buildExcelSafeSubstitute(`$G$${parentRow}`)})`],
              showErrorMessage: false
            };
          }
        }

        listCol++;
      });

      await applyAutoFieldProtection(worksheet, allFields, fieldRowMap);

      const buffer = await workbook.xlsx.writeBuffer();
      saveAs(new Blob([buffer]), `Individual_Basic_Info_Template.xlsx`);
      toast.success("Template downloaded!");
    } catch (downloadError) {
      console.error("[Template] Error:", downloadError);
      toast.error("Template failed");
    }
  };

  const handleImportExcel = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const loadingToast = toast.loading("Parsing Excel file...");
    setUploading(true);

    try {
      const workbook = new ExcelJS.Workbook();
      const arrayBuffer = await file.arrayBuffer();
      await workbook.xlsx.load(arrayBuffer);
      const worksheet = workbook.getWorksheet(1);
      if (!worksheet) throw new Error('No worksheet found in file.');

      const getVal = (cell: ExcelJS.Cell) => {
        if (!cell || cell.value === null || cell.value === undefined) return "";
        if (typeof cell.value === 'object') {
          return (cell.value as any).result || (cell.value as any).richText?.map((t: any) => t.text).join('') || (cell.value as any).text || "";
        }
        return String(cell.value).trim();
      };

      let headerRowIndex = -1;
      worksheet.eachRow((row, rowNumber) => {
        if (headerRowIndex !== -1) return;
        const col1 = getVal(row.getCell(1));
        const col3 = getVal(row.getCell(3));
        if (col1 === '#' || col3 === 'Field') {
          headerRowIndex = rowNumber;
        }
      });

      if (headerRowIndex === -1) {
        throw new Error('Invalid template header. Please use the exported template.');
      }

      const nextFormData = JSON.parse(JSON.stringify(formData));
      const headerRow = worksheet.getRow(headerRowIndex);
      const isRowWise = getVal(headerRow.getCell(3)) === 'Field';

      if (isRowWise) {
        for (let rowIndex = headerRowIndex + 1; rowIndex <= worksheet.rowCount; rowIndex++) {
          const row = worksheet.getRow(rowIndex);
          const label = getVal(row.getCell(3));
          const value = getVal(row.getCell(7));
          if (!label) continue;

          const field = allFields.find((candidate) => candidate.label === label);
          if (!field || isAutoField(field)) continue;
          syncFieldValue(nextFormData, field, value);
        }
      } else {
        const headerMap: Record<string, number> = {};
        headerRow.eachCell((cell, colNumber) => {
          const label = getVal(cell);
          if (label) headerMap[label] = colNumber;
        });

        const dataRow = worksheet.getRow(headerRowIndex + 1);
        if (!dataRow.hasValues) {
          throw new Error("No data found below the header row.");
        }

        allFields.forEach((field) => {
          const colNumber = headerMap[field.label.trim()];
          if (!colNumber || isAutoField(field)) return;
          syncFieldValue(nextFormData, field, getVal(dataRow.getCell(colNumber)));
        });
      }

      const residentialAddress = generateFullResidentialAddress(nextFormData);
      const postalAddress = generateFullPostalAddress(nextFormData);
      nextFormData.full_residential_address = residentialAddress;
      nextFormData.full_postal_address = postalAddress;
      set(nextFormData, 'residential_address_details.full_residential_address', residentialAddress);
      set(nextFormData, 'residential_address_details.current.full_residential_address', residentialAddress);
      set(nextFormData, 'residential_address_details.current.full_address', residentialAddress);
      set(nextFormData, 'postal_address_details.current.full_postal_address', postalAddress);

      setFormData(nextFormData);
      toast.success("Data imported successfully!", { id: loadingToast });
    } catch (importError: any) {
      console.error("[Import] Error:", importError);
      toast.error(`Import failed: ${importError.message}`, { id: loadingToast });
    } finally {
      setUploading(false);
      if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };

  const handleExportExcel = async () => {
    try {
      const workbook = new ExcelJS.Workbook();
      const worksheet = workbook.addWorksheet('Individual Profile');
      const dataSheet = workbook.addWorksheet('DropdownLists');
      dataSheet.state = 'hidden';

      const { optionsMap } = await fetchAllDropdownOptions(allFields);
      prepareSheetBase(worksheet, 'DETAILED INDIVIDUAL INFORMATION REPORT', localIndividual.full_name || 'Individual');

      const fieldsBySection = allFields.reduce((acc, field) => {
        (acc[field.section] = acc[field.section] || []).push(field);
        return acc;
      }, {});

      let currentRow = 5;
      const fieldRowMap: Record<string, number> = {};

      Object.entries(fieldsBySection).forEach(([sectionName, fields]: [string, any]) => {
        fields.forEach((field, index) => {
          fieldRowMap[field.name] = currentRow;
          const value = get(formData, field.dataPath || field.name);
          const displayValue = field.type === 'select' ? resolveDisplayLabel(value, optionsMap[field.name]) : (value || '');
          const row = worksheet.getRow(currentRow);
          row.values = [
            field.id,
            sectionName,
            field.label,
            field.fieldType || field.type || 'text',
            isAutoField(field) ? 'Auto' : 'Manual',
            field.source || 'Client',
            displayValue
          ];

          row.eachCell({ includeEmpty: true }, (cell, colNum) => {
            const customStyle: any = {};
            if (index === 0) customStyle.border = { top: { style: 'medium', color: { argb: EXCEL_COLORS.headerBg } } };
            if (colNum === 7) customStyle.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: EXCEL_COLORS.valueBg } };
            styleCell(cell, customStyle);
          });

          currentRow++;
        });
      });

      applyIndividualAddressFormulas(worksheet, fieldRowMap);

      let listCol = 1;
      allFields.forEach((field) => {
        const rowNum = fieldRowMap[field.name];
        if (!rowNum || field.type !== 'select' || isAutoField(field)) return;

        const optData = optionsMap[field.name];
        const colLetter = dataSheet.getColumn(listCol).letter;

        if (!optData || optData.allOptions.length === 0) {
          dataSheet.getCell(1, listCol).value = "No options found";
          worksheet.getCell(rowNum, 7).dataValidation = { type: 'list', allowBlank: true, formulae: [`DropdownLists!$${colLetter}$1:$${colLetter}$1`] };
        } else if (optData.type === 'standard') {
          optData.allOptions.forEach((option, index) => {
            dataSheet.getCell(index + 1, listCol).value = option.label;
          });
          worksheet.getCell(rowNum, 7).dataValidation = { type: 'list', allowBlank: true, formulae: [`DropdownLists!$${colLetter}$1:$${colLetter}$${optData.allOptions.length}`] };
        } else if (optData.type === 'dependent') {
          const parentRow = fieldRowMap[optData.parentFieldName || ''];
          if (parentRow) {
            Object.entries(optData.manualMapping || {}).forEach(([parentId, children]: [string, any], mappingIndex) => {
              const start = (mappingIndex * 500) + 1;
              const parentLabel = optData.parentValueToLabelMap?.[parentId] || parentId;
              const rangeName = `EXVAL_${toSafeRangeName(field.name)}_${toSafeRangeName(parentLabel)}`;
              children.forEach((child, childIndex) => {
                dataSheet.getCell(start + childIndex, listCol).value = child.label || child.name || child.value;
              });
              workbook.definedNames.add(`DropdownLists!$${colLetter}$${start}:$${colLetter}$${start + children.length - 1}`, rangeName);
            });
            worksheet.getCell(rowNum, 7).dataValidation = {
              type: 'list',
              allowBlank: true,
              formulae: [`=INDIRECT("EXVAL_${toSafeRangeName(field.name)}_"&${buildExcelSafeSubstitute(`$G$${parentRow}`)})`],
              showErrorMessage: false
            };
          }
        }

        listCol++;
      });

      await applyAutoFieldProtection(worksheet, allFields, fieldRowMap);

      const buffer = await workbook.xlsx.writeBuffer();
      saveAs(new Blob([buffer]), `${localIndividual.full_name || 'Individual'}_Basic_Info.xlsx`);
      toast.success("Excel exported successfully!");
    } catch (exportError) {
      console.error("[Export] Error:", exportError);
      toast.error("Export failed");
    }
  };

  const handleExportImage = async (format: 'png' | 'jpeg' | 'pdf') => {
    setIsExporting(true);
    await new Promise(resolve => setTimeout(resolve, 50));
    const exportElement = document.getElementById('export-container');
    if (!exportElement) {
      setIsExporting(false);
      return;
    }
    const canvas = await html2canvas(exportElement, { scale: 2 });
    if (format === 'pdf') {
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`${localIndividual.full_name}_Info.pdf`);
    } else {
      const image = canvas.toDataURL(`image/${format}`, 1.0);
      const link = document.createElement('a');
      link.href = image;
      link.download = `${localIndividual.full_name}_Info.${format}`;
      link.click();
    }
    setIsExporting(false);
  };

  if (error) {
    return <div className="p-8 text-center text-red-600">Error: {error}</div>;
  }

  const middleIndex = Math.ceil(allFields.length / 2);

  return (
    <div ref={componentRef}>
      <input
        type="file" ref={fileInputRef} onChange={handleImportExcel}
        style={{ display: 'none' }} accept=".xlsx, .xls"
      />

      <div className="p-4 border-b border-gray-200">
        <div className="flex justify-between items-center">
          <div>
            <h2 className="text-2xl font-bold text-gray-800">Individual Information</h2>
            <p className="text-sm text-slate-600">View and edit details for {localIndividual?.full_name}.</p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={() => fetchAndSetData()} disabled={isDataLoading}>
              <RefreshCw className={cn("h-4 w-4 mr-2", isDataLoading && "animate-spin")} />
              {isDataLoading ? 'Refreshing...' : 'Refresh'}
            </Button>
            <Button variant="outline" size="sm" onClick={() => fileInputRef.current?.click()} disabled={uploading || loading}>
              <FileUp className="h-4 w-4 mr-2" /> Import
            </Button>
            <Button variant="outline" size="sm" onClick={handleDownloadTemplate} disabled={loading}>
              <Download className="h-4 w-4 mr-2" /> Template
            </Button>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline" size="sm"><Download className="h-4 w-4 mr-2" />Export As</Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuItem onClick={handleExportExcel}><FileSpreadsheet className="h-4 w-4 mr-2" />Excel</DropdownMenuItem>
                <DropdownMenuItem onClick={() => handleExportImage('png')}><ImageIcon className="h-4 w-4 mr-2" />PNG</DropdownMenuItem>
                <DropdownMenuItem onClick={() => handleExportImage('pdf')}><FileText className="h-4 w-4 mr-2" />PDF</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <Button onClick={() => setIsEditMode(!isEditMode)} size="sm" variant="secondary">
              {isEditMode ? <Eye className="h-4 w-4 mr-2" /> : <Edit className="h-4 w-4 mr-2" />}
              {isEditMode ? 'View Mode' : 'Edit Mode'}
            </Button>
            {isEditMode && (
              <Button onClick={handleSaveChanges} size="sm" className="bg-blue-600 hover:bg-blue-700" disabled={isSaving}>
                <Save className="h-4 w-4 mr-2" /> {isSaving ? 'Saving...' : 'Save'}
              </Button>
            )}
          </div>
        </div>
      </div>

      <div className="bg-white overflow-hidden p-4">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <TableSection fields={allFields.slice(0, middleIndex)} formData={formData} handleChange={handleInputChange} isDisabled={!isEditMode} isLoading={isDataLoading || loading} masterFieldsOptions={masterFieldsOptions} dependentOptions={dependentOptions} individual={localIndividual} onHistoryIconClick={(title, data, section) => setHistoryModal({ isOpen: true, title: `${title} History`, data, section })} />
          <TableSection fields={allFields.slice(middleIndex)} formData={formData} handleChange={handleInputChange} isDisabled={!isEditMode} isLoading={isDataLoading || loading} masterFieldsOptions={masterFieldsOptions} dependentOptions={dependentOptions} individual={localIndividual} onHistoryIconClick={(title, data, section) => setHistoryModal({ isOpen: true, title: `${title} History`, data, section })} />
        </div>
      </div>

      {confirmation?.isOpen && (
        <AlertDialog open={confirmation.isOpen} onOpenChange={() => setConfirmation(null)}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>{confirmation.title}</AlertDialogTitle>
              <AlertDialogDescription>{confirmation.description}</AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogAction onClick={() => confirmation.onConfirm('history')}>Archive & Save New</AlertDialogAction>
              <AlertDialogAction onClick={() => confirmation.onConfirm('overwrite')}>Overwrite</AlertDialogAction>
              <AlertDialogCancel onClick={() => setConfirmation(null)}>Cancel</AlertDialogCancel>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      )}

      {clearHistoryConfirmation?.isOpen && (
        <AlertDialog open={clearHistoryConfirmation.isOpen} onOpenChange={() => setClearHistoryConfirmation(null)}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>{clearHistoryConfirmation.title}</AlertDialogTitle>
              <AlertDialogDescription>{clearHistoryConfirmation.description}</AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel onClick={() => setClearHistoryConfirmation(null)}>Cancel</AlertDialogCancel>
              <AlertDialogAction onClick={clearHistoryConfirmation.onConfirm} className="bg-red-600 hover:bg-red-700">Confirm</AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      )}

      <Dialog open={historyModal.isOpen} onOpenChange={(isOpen) => setHistoryModal({ ...historyModal, isOpen })}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>{historyModal.title}</DialogTitle>
          </DialogHeader>
          <div className="max-h-[70vh] overflow-y-auto p-1 pr-4">
            {historyModal.data.length > 0 ? (
              historyModal.data.slice().reverse().map((record, index) => (
                <div key={index} className="mb-4 p-4 border rounded-lg bg-slate-50">
                  <h4 className="font-semibold mb-2 text-gray-600 border-b pb-2">Record #{historyModal.data.length - index}</h4>
                  <HistoryRecordViewer data={record} />
                </div>
              ))
            ) : (
              <p>No history available for this section.</p>
            )}
          </div>
          {historyModal.data.length > 0 && (
            <DialogFooter>
              <Button
                variant="destructive"
                onClick={() => {
                  setClearHistoryConfirmation({
                    isOpen: true,
                    title: "Are you sure?",
                    description: `This will permanently delete all ${historyModal.data.length} historical records for "${historyModal.section}". This action cannot be undone.`,
                    onConfirm: () => handleClearHistory(historyModal.section),
                  });
                }}
              >
                <Trash2 className="h-4 w-4 mr-2" />
                Clear All History
              </Button>
            </DialogFooter>
          )}
        </DialogContent>
      </Dialog>

      {isExporting && (
        <div id="export-container" style={{ position: 'absolute', left: '-9999px', top: 0, width: '1200px', padding: '20px', backgroundColor: 'white' }}>
          <h1 style={{ fontSize: '24px', fontWeight: 'bold', marginBottom: '16px', textAlign: 'center' }}>
            Individual Information: {localIndividual?.full_name}
          </h1>
          <TableSection
            fields={allFields}
            formData={formData}
            isExporting={true}
            masterFieldsOptions={masterFieldsOptions}
            dependentOptions={dependentOptions}
            isDisabled={true}
            isLoading={false}
          />
        </div>
      )}
    </div>
  )
}

